/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookingHistory.java
 *
 * Created on Jul 12, 2018, 9:21:50 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
public class BookingHistory extends javax.swing.JFrame {

    /** Creates new form BookingHistory */
    public BookingHistory() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - BOOKING HISTORY");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel7.setText("Booking History");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Back....");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train Number", "DOB", "DOJ", "PNR", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setLocationRelativeTo(null);
        jf32.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        BookingHistory1 jfct = new BookingHistory1();
        DefaultTableModel m = (DefaultTableModel) jfct.jTable1.getModel();
        int index = jTable1.getSelectedRow();
        TableModel m1 = jTable1.getModel();
        String pos = m1.getValueAt(index, 4).toString();
        String p = m1.getValueAt(index, 3).toString();
        String tn = "";
        String tna = "";
        String s = "";
        String d = "";
        String date = "";
        String dtime = "";
        String n = "";
        String a = "";
        String g = "";
        String b = "";
        String ct = "";
        String sn = "";
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           if(!pos.equalsIgnoreCase("Cancelled")){
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from booking b, train t where b.pnr = '" + p + "' and b.trainno = t.trainno order by seatn desc");
           while(rs.next()){
               tn = rs.getString("trainno");
               tna = rs.getString("t_name");
               s = rs.getString("source");
               d = rs.getString("destination");
               date = rs.getString("DOJ");
               dtime = rs.getString("depttime");
               n = rs.getString("Name");
               a = rs.getString("Age");
               g = rs.getString("Gender");
               b = rs.getString("Birth");
               ct = rs.getString("CoachType");
               sn = rs.getString("Seatn");
               jfct.jTextField1.setText(tn);
               jfct.jTextField7.setText(tna);
               jfct.jTextField2.setText(s);
               jfct.jTextField3.setText(d);
               jfct.jTextField6.setText(dtime);
               SimpleDateFormat sd1 = new SimpleDateFormat("yyyy-MM-dd");
               Date d3 = sd1.parse(date);
               SimpleDateFormat sd2 = new SimpleDateFormat("yyyy-MM-dd");
               String d4 = sd2.format(d3);
               jfct.jTextField5.setText(d4 + "");
               jfct.jTextField4.setText(p);
               m.addRow(new Object[] {n,a,g,b,ct,sn});
            }
               dispose();
        jfct.setLocationRelativeTo(null);
               jfct.setVisible(true);
            }
 else {
    Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from cancelticket b, train t where b.pnr = '" + p + "' and b.trainno = t.trainno order by seatn desc");
           while(rs.next()){
               tn = rs.getString("trainno");
               tna = rs.getString("t_name");
               s = rs.getString("source");
               d = rs.getString("destination");
               date = rs.getString("DOJ");
               dtime = rs.getString("depttime");
               n = rs.getString("Name");
               a = rs.getString("Age");
               g = rs.getString("Gender");
               b = rs.getString("Birth");
               ct = rs.getString("CoachType");
               sn = rs.getString("Seatn");
               jfct.jTextField1.setText(tn);
               jfct.jTextField7.setText(tna);
               jfct.jTextField2.setText(s);
               jfct.jTextField3.setText(d);
               jfct.jTextField6.setText(dtime);
               SimpleDateFormat sd1 = new SimpleDateFormat("yyyy-MM-dd");
               Date d3 = sd1.parse(date);
               SimpleDateFormat sd2 = new SimpleDateFormat("yyyy-MM-dd");
               String d4 = sd2.format(d3);
               jfct.jTextField5.setText(d4 + "");
               jfct.jTextField4.setText(p);
               m.addRow(new Object[] {n,a,g,b,ct,sn});
            }
               dispose();
        jfct.setLocationRelativeTo(null);
               jfct.setVisible(true);
 }
           }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
