/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FPassword.java
 *
 * Created on Aug 10, 2018, 10:58:33 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
public class FPassword extends javax.swing.JFrame {

    /** Creates new form FPassword */
    public FPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - FORGET PASSWORD");

        jPanel1.setBackground(new java.awt.Color(-65536,true));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 66, 69);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 10, 71, 24);

        jLabel3.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel3.setText("ForgetPassword");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 40, 238, 25);

        jLabel1.setText("User Name:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 100, 130, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 100, 300, 40);

        jLabel2.setText("Security Answer:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 200, 130, 40);

        jButton2.setText("Verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 250, 140, 30);

        jLabel6.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel6.setText("Back....");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 260, 90, 25);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 200, 300, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Security Question*", "What is your Pet name?", "What is the name of the first school that you studied?", "Who was your childhood hero?", "What is your Father NickName?" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 150, 300, 40);

        jLabel7.setText("Select Security Question:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 150, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ui = jTextField1.getText();
        String sq = jComboBox1.getSelectedItem().toString();
        String sqa = jTextField2.getText();
        String c = "";
         try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from signup where username = '" + ui + "' and SQues = '" + sq + "' and SAns = '" + sqa + "'");
           if(rs.next()){
              c = rs.getString("Password");
              JOptionPane.showMessageDialog(null, "Your Password is: " + c);
              dispose();
              new JFrame1().setVisible(true);
           }
 else
     JOptionPane.showMessageDialog(null, "Enter Correct Credentials");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame1 jf26 = new JFrame1();
        jf26.setLocationRelativeTo(null);
        jf26.setVisible(true);
}//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
