/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame4.java
 *
 * Created on 29 Apr, 2018, 9:17:14 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
public class JFrame4 extends javax.swing.JFrame {

    /** Creates new form JFrame4 */
    public JFrame4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - SIGN UP PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 70, 30);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 110, 87, 27);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 110, 30);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 260, 110, 30);

        jTextField1.setText("First Name*");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 110, 120, 30);

        jTextField2.setText("Last Name*");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(330, 110, 110, 30);

        jTextField3.setText("User Name*");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(150, 220, 140, 30);

        jButton1.setText("Sign Up!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 490, 130, 23);

        jLabel7.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel7.setText("Sign Up here");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 40, 149, 25);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(150, 260, 140, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 11, 66, 69);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(380, 10, 71, 24);

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Back....");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(690, 480, 74, 25);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 70, 30);

        jTextField4.setText("Country*");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(100, 150, 120, 30);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 110, 110, 26);

        jTextField5.setText("Mobile Number*");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(560, 110, 110, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 300, 130, 30);

        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(150, 300, 140, 30);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 150, 90, 30);

        jTextField6.setText("E-Mail*");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(330, 150, 340, 30);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 210, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Security Question*", "What is your Pet name?", "What is the name of the first school that you studied?", "Who was your childhood hero?", "What is your Father NickName?" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(340, 240, 420, 40);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 290, 110, 30);

        jTextField7.setText("Security Answer*");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(450, 290, 200, 30);

        jLabel13.setText("----Personal Details-----------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 90, 790, 14);

        jLabel14.setText("----Contact Details------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 340, 800, 14);

        jLabel15.setText("----Individual Registration---------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 196, 800, 14);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 370, 140, 30);

        jTextField8.setText("Town/City/Pincode*");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(170, 450, 440, 30);

        jTextField9.setText("Door No./Plot No.*");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(170, 370, 440, 30);

        jTextField10.setText("Street/Nagar*");
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(170, 410, 440, 30);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(30, 410, 140, 30);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 450, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fn = jTextField1.getText();
        String ln = jTextField2.getText();
        String ui = jTextField3.getText();
        String co = jTextField4.getText();
        String mn = jTextField5.getText();
        String sq = jComboBox1.getSelectedItem().toString();
        String sqa = jTextField7.getText();
        String em = jTextField6.getText();
        String a1 = jTextField9.getText();
        String a2 = jTextField10.getText();
        String a3 = jTextField8.getText();
        int mni = mn.length();
        int uil = ui.length();
        String pw1 = jPasswordField1.getText();
        String pw2 = jPasswordField2.getText();
        int pwi = pw1.length();
        if(fn.length() > 0 && ln.length() > 0 && ui.length() >= 8 && co.length() > 0 && mni == 10 && sqa.length() > 0 && em.length() > 0 && a1.length() > 0 && a2.length() > 0 && a3.length() > 0){
        if(!sq.equalsIgnoreCase("Select a Security Question*")){
        if(pw1.equals(pw2)){
         try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st1 = con.createStatement();
           ResultSet rs = st1.executeQuery("Select * from signup where username = '" + ui + "'");
           if(!rs.next()){
           Statement st = con.createStatement();
           if(uil > 8 && pwi > 8 && mni == 10){
           st.executeUpdate("Insert into signup values('" + fn + "','" + ln + "','" + ui + "','" + pw1 + "',curdate(),'" + mn + "','" + co + "','" + em + "','" + sq + "','" + sqa + "','" + a1 + "," + a2 + "," + a3 + "')");
           st.executeUpdate("Insert into login values('" + ui + "','" + pw1 + "')");
           JOptionPane.showMessageDialog(null, "You have sucessfully signed up");
           dispose();
           JFrame1 jf1 = new JFrame1();
           jf1.setVisible(true);
           }
           else
               JOptionPane.showMessageDialog(null, "Enter a Strong Credentials");
             }
           else
               JOptionPane.showMessageDialog(null, "User Name already Exits");
           }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }
 else
     JOptionPane.showMessageDialog(null, "Enter a right Password");
        }
 else
     JOptionPane.showMessageDialog(null, "Please Select a Security Question");
        }
 else
     JOptionPane.showMessageDialog(null, "Enter all Required Field appropriately");
    }//GEN-LAST:event_jButton1ActionPerformed
int np = 0;
    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        np++;
        if(np == 1){
        jLabel4.setText("Password*");
        jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame1 jf1 = new JFrame1();
        jf1.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
int n1 = 0;
    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        // TODO add your handling code here:
        n1++;
        if(n1 == 1){
        jLabel8.setText("Re-Type Password*");
        jPasswordField2.setText("");
        }
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed
int n2 = 0;
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        n2++;
        if(n2 == 1){
        jLabel1.setText("First Name*");
        jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1MouseClicked
int n3 = 0;
    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        n3++;
        if(n3 == 1){
        jLabel2.setText("Last Name*");
        jTextField2.setText("");
        }
    }//GEN-LAST:event_jTextField2MouseClicked
int n4 = 0;
    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        n4++;
        if(n4 == 1){
        jLabel5.setText("Country*");
        jTextField4.setText("");
        }
    }//GEN-LAST:event_jTextField4MouseClicked
int n5 = 0;
    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
        n5++;
        if(n5 == 1){
        jLabel6.setText("Mobile Number*");
        jTextField5.setText("");
        }
    }//GEN-LAST:event_jTextField5MouseClicked
int n6 = 0;
    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        n6++;
        if(n6 == 1){
        jLabel3.setText("User Name*");
        jTextField3.setText("");
        }
    }//GEN-LAST:event_jTextField3MouseClicked
int n7 = 0;
    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
        n7++;
        if(n7 == 1){
        jLabel9.setText("E-Mail*");
        jTextField6.setText("");
        }
    }//GEN-LAST:event_jTextField6MouseClicked
int n8 = 0;
    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        n8++;
        if(n8 == 1){
        jLabel10.setText("Secret Question*");
        }
    }//GEN-LAST:event_jComboBox1MouseClicked
int n9 = 0;
    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        n9++;
        if(n9 == 1){
        jLabel11.setText("Security Answer*");
        jTextField7.setText("");
        }
    }//GEN-LAST:event_jTextField7MouseClicked
int n10 = 0;
    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
        n10++;
        if(n10 == 1){
        jLabel18.setText("Door No./Plot No.*");
        jTextField9.setText("");
        }
    }//GEN-LAST:event_jTextField9MouseClicked
int n11 = 0;
    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        // TODO add your handling code here:
        n11++;
        if(n11 == 1){
        jLabel19.setText("Street/Nagar*");
        jTextField10.setText("");
        }
    }//GEN-LAST:event_jTextField10MouseClicked
int n12 = 0;
    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:
        n12++;
        if(n12 == 1){
        jLabel20.setText("Town/City/Pincode*");
        jTextField8.setText("");
        }
    }//GEN-LAST:event_jTextField8MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
