/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame48.java
 *
 * Created on 12 Jun, 2018, 8:08:10 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner.*;
import java.sql.*;
import javax.swing.*;
public class JFrame48 extends javax.swing.JFrame {

    /** Creates new form JFrame48 */
    public JFrame48() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - TRAIN SEARCH DETAILS");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel7.setText("Train Details");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train No.", "Train Name", "Source", "Desitination", "KMs", "Departure Time", "Amount 3A/Ticket", "Amount 2A/Ticket", "Amount 1A/Ticket", "Amount Sleeper/ Ticket"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(1).setMinWidth(0);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(150);

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Back....");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(485, 485, 485)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(528, 528, 528)
                                .addComponent(jLabel6))))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dispose();
        TicketBooking jf3 = new TicketBooking();
        jf3.setVisible(true);
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        jf3.jTextField5.setText(model.getValueAt(index, 1).toString());
        jf3.jTextField6.setText(model.getValueAt(index, 5).toString());
        String trainno = model.getValueAt(index, 0).toString();
        String source = model.getValueAt(index, 2).toString();
        String destination = model.getValueAt(index, 3).toString();
        int nt = Integer.parseInt(JFrame2.jComboBox4.getSelectedItem().toString());
        String yy = JFrame2.jComboBox1.getSelectedItem().toString();//YYYY
        String mm = JFrame2.jComboBox2.getSelectedItem().toString();//MM
        String dd = JFrame2.jComboBox3.getSelectedItem().toString();//DD
        String date = yy + "-" + mm + "-" + dd;
        String datedept = "";
        int coachno = 0;int isn = 0;
        String sn = "";
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st1 = con.createStatement();
           ResultSet rs1 = st1.executeQuery("Select depttime from train where trainno = " + trainno);
           if(rs1.next()){
              datedept = date + " " + rs1.getString("depttime");
           }
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select substr(coachtype,2,2) from booking where trainno = " + trainno + " and doj = '" + datedept + "' order by coachtype desc");
           if(rs.next()){
               coachno = Integer.parseInt(rs.getString("substr(coachtype,2,2)"));
           }
           Statement st2 = con.createStatement();
           ResultSet rs2 = st2.executeQuery("Select * from booking where trainno = " + trainno + " and doj = '" + datedept + "' and coachtype like('S%')order by seatn desc");
           if(rs2.next()){
              sn = rs2.getString("seatn");
              isn = Integer.parseInt(sn) + nt;
              if(isn >= 73){
                 coachno++;
              }
              if(coachno == 13){
              jf3.jRadioButton4.setEnabled(false);
               }
           Statement st5 = con.createStatement();
           ResultSet rs5 = st5.executeQuery("Select * from booking where trainno = " + trainno + " and doj = '" + datedept + "' and coachtype = '3A' order by seatn desc");
           if(rs5.next()){
              sn = rs5.getString("seatn");
              isn = Integer.parseInt(sn) + nt;
              if(isn >= 73){
              jf3.jRadioButton3.setEnabled(false);
               }
               }
           Statement st6 = con.createStatement();
           ResultSet rs6 = st6.executeQuery("Select * from booking where trainno = " + trainno + " and doj = '" + datedept + "' and coachtype = '2A' order by seatn desc");
           if(rs6.next()){
              sn = rs6.getString("seatn");
              isn = Integer.parseInt(sn) + nt;
              if(isn >= 73){
              jf3.jRadioButton2.setEnabled(false);
               }
               }
           Statement st7 = con.createStatement();
           ResultSet rs7 = st7.executeQuery("Select * from booking where trainno = " + trainno + " and doj = '" + datedept + "' and coachtype = '1A' order by seatn desc");
           if(rs7.next()){
              sn = rs7.getString("seatn");
              isn = Integer.parseInt(sn) + nt;
              if(isn >= 73){
              jf3.jRadioButton1.setEnabled(false);
               }
               }
            }
        }
        catch(Exception e){
         }
                    TicketBooking.jTextField1.setText(trainno);
                    TicketBooking.jTextField2.setText(source);
                    TicketBooking.jTextField3.setText(destination);
                    TicketBooking.jTextField4.setText(date);
                    TicketBooking.jLabel6.setText(nt + "");
                    jf3.jLabel6.setVisible(false);
                    jf3.jLabel10.setText(JFrame1.jTextField1.getText());
                    jf3.jLabel10.setVisible(false);
                    int i = 1;
                while(i <= nt){
                    DefaultTableModel model1 = (DefaultTableModel) TicketBooking.jTable1.getModel();
                    model1.addRow(new Object[]{});
                    i++;
                }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame48().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
