/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame18.java
 *
 * Created on 30 Apr, 2018, 5:54:51 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
public class JFrame18 extends javax.swing.JFrame {

    /** Creates new form JFrame18 */
    public JFrame18() {
        initComponents();
        double r = Double.parseDouble(TicketBookingConformation.jTextField10.getText());
        double rtax = r * 0.05;
        jLabel11.setText(r + "");
        jLabel13.setText(Math.round(rtax * 100.0) / 100.0 + "");
        jLabel15.setText((r + Math.round(rtax * 100.0) / 100.0) + "");
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("USER - ICICI NET BANKING GATEWAY");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel10.setText("Net Banking details");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(133, 53, 237, 25);

        jLabel1.setText("Welcome To your ICICI Net Banking ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 80, 240, 14);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 230, 90, 23);

        jLabel2.setText("UserName:-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(68, 117, 80, 14);

        jLabel3.setText("Password:-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(68, 143, 80, 14);

        jLabel4.setText("Acc.No:-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(68, 169, 80, 14);

        jLabel5.setText("Remark:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(68, 195, 80, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(153, 114, 113, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(153, 166, 113, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(153, 192, 113, 20);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(153, 140, 111, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 11, 66, 69);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 11, 71, 36);

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Back....");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(324, 270, 100, 25);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(179, 230, 90, 23);

        jPanel2.setLayout(null);

        jLabel9.setText("Fare:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 40, 50, 20);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 40, 70, 25);

        jLabel14.setText("TOTAL:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 90, 50, 30);

        jLabel16.setText("BILL SUMMARY");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 10, 100, 24);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 90, 70, 30);

        jLabel17.setText("GST(5%):");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 70, 70, 20);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 70, 70, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 110, 140, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a = jTextField1.getText();
        String b = jPasswordField1.getText();
        String c = jTextField3.getText();
        int f = a.length();
        int g = b.length();
        int h = c.length();
        if(f > 6 && g > 8 && h == 13){
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           st.executeUpdate("Insert into nb values('" + jTextField1.getText() + "','" + jPasswordField1.getText() + "'," + jTextField3.getText() + ",'" + jTextField4.getText() + "'," + jLabel15.getText() + ")");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
           dispose();
           JFrame22 jf22 = new JFrame22();
           jf22.setVisible(true);
        }
        else
            javax.swing.JOptionPane.showMessageDialog(null, "Please Enter a Valid Detail");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame9 jf9 = new JFrame9();
        jf9.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int pnr = Integer.parseInt(TicketBookingConformation.jLabel11.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
            Statement st = con.createStatement();
            st.executeUpdate("delete from booking where pnr = " + pnr);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame18().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
