/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame6.java
 *
 * Created on 30 Apr, 2018, 1:03:09 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
public class JFrame6 extends javax.swing.JFrame {

    /** Creates new form JFrame6 */
    public JFrame6() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("USER - MODE OF PAYMENT");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("Payment Mode:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(319, 100, 110, 14);

        jRadioButton1.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Credit Card");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(440, 100, 130, 23);

        jRadioButton2.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Debit Card");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(440, 130, 130, 23);

        jRadioButton3.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Net Banking");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(440, 160, 130, 23);

        jLabel10.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel10.setText("Payment Mode");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 40, 178, 25);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 210, 110, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 20, 66, 69);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(410, 10, 71, 24);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\payment.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 880, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
           dispose();
           JFrame7 jf7 = new JFrame7();
           jf7.setVisible(true);
        }
        else
            if(jRadioButton2.isSelected()){
           dispose();
           JFrame8 jf8 = new JFrame8();
           jf8.setVisible(true);
        }
            else
                if(jRadioButton3.isSelected()){
           dispose();
           JFrame9 jf9 = new JFrame9();
           jf9.setVisible(true);
        }
                else
                    JOptionPane.showMessageDialog(null, "Please select a payment mode");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables

}
