/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame2.java
 *
 * Created on 29 Apr, 2018, 6:10:04 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner.*;
import java.sql.*;
import javax.swing.*;
public class JFrame2 extends javax.swing.JFrame {

    /** Creates new form JFrame2 */
    public JFrame2() {
        initComponents();
        this.setLocationRelativeTo(null);
        String s = "";
        String d = "";
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from ikm");
           while(rs.next()){
               s = rs.getString("FromTo");
               d = rs.getString("FromTo");
               boolean exists1 = false;
               for (int index = 0; index < JFrame2.jComboBox5.getItemCount() && !exists1; index++) {
               if (s.equals(JFrame2.jComboBox5.getItemAt(index))) {
                       exists1 = true;
               }
               }
               if (!exists1) {
                   JFrame2.jComboBox5.addItem(s);
               }
               boolean exists2 = false;
               for (int index = 0; index < JFrame2.jComboBox6.getItemCount() && !exists2; index++) {
               if (d.equals(JFrame2.jComboBox6.getItemAt(index))) {
                       exists2 = true;
               }
               }
               if (!exists2) {
                   JFrame2.jComboBox6.addItem(d);
               }
   }
           Statement stc = con.createStatement();
           ResultSet rsc = stc.executeQuery("Select curdate()");
           if(rsc.next()) {
              String str = rsc.getString(1);
              jComboBox1.addItem(str.substring(0,4));
            }
           Statement sta = con.createStatement();
           ResultSet rsa = sta.executeQuery("Select curdate() + interval 90 day");
           if(rsa.next()) {
                  String str = rsa.getString(1);
                  if(!jComboBox1.getItemAt(0).equals(str.substring(0,4)))
                  jComboBox1.addItem(str.substring(0,4));
           }
           Statement st1 = con.createStatement();
           ResultSet rs1 = st1.executeQuery("select Date_Format(curdate(),'%Y')");
           if(rs1.next()){
              JFrame2.jComboBox1.setSelectedItem(rs1.getString("Date_Format(curdate(),'%Y')") + "");
           }
           Statement st2 = con.createStatement();
           ResultSet rs2 = st2.executeQuery("select Date_Format(curdate(),'%m')");
           if(rs2.next()){
              JFrame2.jComboBox2.setSelectedItem(rs2.getString("Date_Format(curdate(),'%m')"));
           }
           Statement st3 = con.createStatement();
           ResultSet rs3 = st3.executeQuery("select Date_Format(curdate() + interval 1 day,'%d')");
           if(rs3.next()){
              JFrame2.jComboBox3.setSelectedItem(rs3.getString("Date_Format(curdate() + interval 1 day,'%d')"));
           }
        }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - TRAIN SEARCH WINDOW");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("To:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 140, 50, 14);

        jLabel2.setText("From:-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 110, 49, 14);

        jLabel3.setText("Date(YY/MM/DD):-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 170, 100, 14);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 240, 110, 23);

        jLabel7.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel7.setText("Welcome to Your Booking");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 70, 303, 25);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(460, 170, 70, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(530, 170, 60, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(590, 170, 60, 20);

        jLabel8.setText("Number of Tickets:-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 200, 130, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(460, 200, 70, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 20, 66, 69);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 10, 71, 38);

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Back....");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(540, 320, 74, 25);

        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(460, 110, 190, 20);

        jComboBox6.setToolTipText("");
        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox6MouseClicked(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(460, 140, 190, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\main-qimg-2d4edf2ccf0f1b3dcdeb7b0cc094f37b-c.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 310, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a = jComboBox5.getSelectedItem().toString();//Source
        String b = jComboBox6.getSelectedItem().toString();//Destination
        String yy = jComboBox1.getSelectedItem().toString();//YY
        String mm = jComboBox2.getSelectedItem().toString();//MM
        String dd = jComboBox3.getSelectedItem().toString();//DD
        String datedate = yy + "-" + mm + "-" + dd;
        String threedate = "";
        int dcheck = 0;
        if(!a.equals(b)){
         try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement sdt = con.createStatement();
           ResultSet rsdt = sdt.executeQuery("select curdate() + interval 90 day");
           if(rsdt.next()){
              threedate = rsdt.getString("curdate() + interval 90 day");
   try{
   SimpleDateFormat sd = new SimpleDateFormat("yy-MM-dd");
   Date d3 = sd.parse(datedate);
   Date d4 = sd.parse(threedate);
   if(d3.before(d4)){
       dcheck = 1;
   }
       }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
           }
        }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
        String cdate = "";
        int n = 0;
        String ms = "";//Message Source
        String md = "";//Message Destination
        String mt = "";//Message Train Number
        String mtn = "";//Train Name
        String dtime = "";//Departure Time
        int km = 0;
        double r1a = 0;
        double r2a = 0;
        double r3a = 0;
        double rsl = 0;
        int nt = Integer.parseInt(jComboBox4.getSelectedItem().toString());
         try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           st.executeUpdate("Insert into search values('" + a + "','" + b + "','" + yy + "-" + mm + "-" + dd + "', curDate(), '" + nt + "')");
           ResultSet rs = st.executeQuery("Select * from train where IStation like('%" + a + "%') and IStation like('%" + b + "%')");
           if(rs.next()){
           ms = rs.getString("Source");
           md = rs.getString("Destination");
           mt = rs.getString("Trainno");
           Statement st1 = con.createStatement();
           ResultSet rs1 = st.executeQuery("Select DATE_FORMAT(curdate(), '%y-%m-%d')");
           if(rs1.next()){
              cdate = rs1.getString("DATE_FORMAT(curdate(), '%y-%m-%d')");
           }
   try{
   SimpleDateFormat sd = new SimpleDateFormat("yy-MM-dd");
   Date d1 = sd.parse(datedate);
   Date d2 = sd.parse(cdate);
   if(d1.after(d2)){
       n = 1;
   }
       }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
   if(n == 1 && dcheck == 1){
           dispose();
           JFrame48 jf48 = new JFrame48();
           DefaultTableModel model = (DefaultTableModel) JFrame48.jTable1.getModel();
           Statement st2 = con.createStatement();
           ResultSet rs2 = st.executeQuery("Select t.*,k." + b + ",d." + b + " as depttime1 from ikm k, train t, idept d where k.fromto = '" + a + "' and d.fromto = '" + a + "' and t.IStation like('%" + a + "%') and t.IStation like('%" + b + "%')");
           if(rs2.next()){
           ms = rs2.getString("Source");
           md = rs2.getString("Destination");
           mt = rs2.getString("Trainno");
           mtn = rs2.getString("T_Name");
           dtime = rs2.getString("depttime1");
           r1a = Double.parseDouble(rs2.getString("R1A"));
           r2a = Double.parseDouble(rs2.getString("R2A"));
           r3a = Double.parseDouble(rs2.getString("R3A"));
           rsl = Double.parseDouble(rs2.getString("RS"));
           km = Integer.parseInt(rs2.getString(b));
           model.addRow(new Object[]{mt,mtn,a,b,km,dtime,r3a * km,r2a * km,r1a * km,rsl * km});
   }
           jf48.setVisible(true);
               }
           else
               JOptionPane.showMessageDialog(null, "Select a valid date");
             }
           else
               JOptionPane.showMessageDialog(null, "No Train with the specific source and destination exits");
           }
           catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }
 else
     JOptionPane.showMessageDialog(null, "Please Select a different Source/Destination");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        //jComboBox6.removeItem(jComboBox5.getSelectedItem());
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6MouseClicked

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        //jComboBox5.removeItem(jComboBox6.getSelectedItem());
    }//GEN-LAST:event_jComboBox6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JComboBox jComboBox3;
    public static javax.swing.JComboBox jComboBox4;
    public static javax.swing.JComboBox jComboBox5;
    public static javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
