/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame29.java
 *
 * Created on 8 Jun, 2018, 11:51:23 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class JFrame29 extends javax.swing.JFrame {

    /** Creates new form JFrame29 */
    public JFrame29() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN - HOME PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jButton1.setText("Add Train");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete Train");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel3.setText("Welcome to AIRCTC");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N

        jButton3.setText("Change Rate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Log Out");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jButton4.setText("Prepare Chart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Show Cancelled Tickets");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame30 jf30 = new JFrame30();
        jf30.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame31 jf31 = new JFrame31();
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st4 = con.createStatement();
           ResultSet rs4 = st4.executeQuery("select * from train");
           while(rs4.next()){
               String tn = rs4.getString("TrainNo");
              JFrame31.jComboBox4.addItem(tn);
           }
        }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
        jf31.setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        RateChange jf31 = new RateChange();
        jf31.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame26 jf26 = new JFrame26();
        jf26.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Chart c = new Chart();
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st1 = con.createStatement();
           ResultSet rs1 = st1.executeQuery("select Date_Format(curdate(),'%y')");
           if(rs1.next()){
              Chart.jComboBox1.setSelectedItem(rs1.getString("Date_Format(curdate(),'%y')") + "");
           }
           Statement st2 = con.createStatement();
           ResultSet rs2 = st2.executeQuery("select Date_Format(curdate(),'%m')");
           if(rs2.next()){
              Chart.jComboBox2.setSelectedItem(rs2.getString("Date_Format(curdate(),'%m')"));
           }
           Statement st3 = con.createStatement();
           ResultSet rs3 = st3.executeQuery("select Date_Format(curdate(),'%d')");
           if(rs3.next()){
              Chart.jComboBox3.setSelectedItem(rs3.getString("Date_Format(curdate(),'%d')"));
        }
           Statement st4 = con.createStatement();
           ResultSet rs4 = st4.executeQuery("select * from train");
           while(rs4.next()){
               String tn = rs4.getString("TrainNo");
              Chart.jComboBox4.addItem(tn);
           }
        }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
        dispose();
        c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CancelledTicket cct = new CancelledTicket();
        DefaultTableModel model = (DefaultTableModel) cct.jTable1.getModel();
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st1 = con.createStatement();
           ResultSet rs1 = st1.executeQuery("select * from CancelTicket");
           while(rs1.next()){
              String tn = rs1.getString("Trainno");
              String pn = rs1.getString("Pnr");
              String n = rs1.getString("Name");
              String a = rs1.getString("Age");
              String g = rs1.getString("Gender");
              String b = rs1.getString("Birth");
              String ct = rs1.getString("CoachType");
              String sea = rs1.getString("SeatN");
              String d = rs1.getString("DOJ");
              model.addRow(new Object[] {tn,pn,n,a,g,b,ct,sea,d});
           }
           dispose();
           cct.setVisible(true);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame29().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
