/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame13.java
 *
 * Created on 30 Apr, 2018, 5:32:04 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner.*;
import java.sql.*;
import javax.swing.*;
public class JFrame13 extends javax.swing.JFrame {

    /** Creates new form JFrame13 */
    public JFrame13() {
        initComponents();
        double r = Double.parseDouble(TicketBookingConformation.jTextField10.getText());
        double rtax = r * 0.05;
        jLabel11.setText(r + "");
        jLabel13.setText(Math.round(rtax * 100.0) / 100.0 + "");
        jLabel15.setText((r + Math.round(rtax * 100.0) / 100.0) + "");
        this.setLocationRelativeTo(null);
        int cd = 0, ca = 0;
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
            Statement stc = con.createStatement();
            ResultSet rsc = stc.executeQuery("Select curdate()");
            if(rsc.next()) {
               cd = Integer.parseInt(rsc.getString(1).substring(0, 4));
               jComboBox2.addItem(cd);
            }
            Statement sta = con.createStatement();
            ResultSet rsa = sta.executeQuery("Select curdate() + interval 3650 day");
            if(rsa.next()) {
               ca = Integer.parseInt(rsa.getString(1).substring(0, 4));
            }
            for(int i = 1; i <= (ca - cd); i++) {
               jComboBox2.addItem((cd + i));
            }
   }
   catch(Exception ex){
      JOptionPane.showMessageDialog(null, ex.getMessage());
   }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("USER - HDFC CREDIT CARD GATEWAY");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel10.setText("Credit Card details");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(161, 41, 270, 25);

        jLabel1.setText("Welcome To your HDFC Credit Card ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 70, 210, 14);

        jLabel2.setText("Card Number:-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(64, 109, 120, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(213, 109, 137, 20);

        jLabel3.setText("Expiry Date(MM/YYYY):-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(64, 140, 140, 14);

        jLabel5.setText("Card Holders Name:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(64, 169, 140, 14);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(213, 166, 137, 20);

        jLabel6.setText("Transcation Password:-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(64, 195, 140, 14);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 250, 100, 23);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(213, 192, 137, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(213, 140, 59, 20);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(278, 140, 72, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 11, 66, 69);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(239, 11, 71, 25);

        jLabel8.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel8.setText("Back....");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 270, 100, 25);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 250, 110, 23);

        jPanel2.setLayout(null);

        jLabel9.setText("Fare:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 40, 50, 20);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 40, 70, 25);

        jLabel12.setText("GST(5%):");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 70, 70, 20);

        jLabel14.setText("TOTAL:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 100, 50, 20);

        jLabel16.setText("BILL SUMMARY");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 10, 100, 24);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 70, 70, 20);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 100, 70, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 90, 140, 130);

        jLabel17.setText("CVV:-");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 220, 150, 14);

        jPasswordField2.setText("CVV");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(210, 220, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a = jTextField1.getText();
        String b = jComboBox1.getSelectedItem().toString();
        String c = jComboBox2.getSelectedItem().toString();
        String d = jTextField4.getText();
        String e = jPasswordField1.getText();
        String x = jPasswordField2.getText();
        int y = x.length();
        double ramt = Double.parseDouble(jLabel15.getText());
        int f = a.length();
        int g = b.length();
        int h = c.length();
        int i = d.length();
        int j = e.length();
        String datedate = c + "-" + b;
        String cdate = "";
        int n = 0;
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
            Statement st = con.createStatement();
            ResultSet rs1 = st.executeQuery("SELECT DATE_FORMAT(curdate(), '%Y-%m')");
            if(rs1.next()){
                cdate = rs1.getString("DATE_FORMAT(curdate(), '%Y-%m')");
            }
            SimpleDateFormat sd = new SimpleDateFormat("yy-mm");
            Date d1 = sd.parse(datedate);
            Date d2 = sd.parse(cdate);
            if(d1.after(d2)){
                n = 1;
            } else
                if(d1.equals(d2)){
                    n = 1;
                }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        if(n == 1){
            if(f == 16 && g == 2 && h == 4 && i > 0 && j > 0 && y == 3){
                try{
                    Class.forName("java.sql.DriverManager");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
                    Statement st = con.createStatement();
                    st.executeUpdate("Insert into cc values(" + jTextField1.getText() + "," + jComboBox1.getSelectedItem().toString() + "," + jComboBox2.getSelectedItem().toString() + ",'" + jTextField4.getText() + "','"  + jPasswordField1.getText() + "'," + x + "," + ramt +")");
                } catch(Exception ey){
                    JOptionPane.showMessageDialog(null, ey.getMessage());
                }
                dispose();
                JFrame22 jf22 = new JFrame22();
                jf22.setLocationRelativeTo(null);
                jf22.setVisible(true);
            } else
                javax.swing.JOptionPane.showMessageDialog(null, "Please Enter a Valid Detail");
        } else
            JOptionPane.showMessageDialog(null, "Please Select a valid Date");
}//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.setText("");
}//GEN-LAST:event_jPasswordField1MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame7 jf7 = new JFrame7();
        jf7.setLocationRelativeTo(null);
        jf7.setVisible(true);
}//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int pnr = Integer.parseInt(TicketBookingConformation.jLabel11.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
            Statement st = con.createStatement();
            st.executeUpdate("delete from booking where pnr = " + pnr);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        // TODO add your handling code here:
        jPasswordField2.setText("");
}//GEN-LAST:event_jPasswordField2MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
