/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame22.java
 *
 * Created on 30 Apr, 2018, 6:18:21 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class JFrame22 extends javax.swing.JFrame {

    /** Creates new form JFrame22 */
    public JFrame22() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - THANKYOU PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel10.setText("Conformation Report");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 50, 261, 25);

        jLabel11.setFont(new java.awt.Font("Ravie", 2, 12));
        jLabel11.setText("Thank you for your Booking from AIRCTC");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 250, 327, 17);

        jLabel12.setFont(new java.awt.Font("Ravie", 2, 12));
        jLabel12.setText("Have a safe Journey!!");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 270, 174, 17);

        jButton1.setText("Print Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 310, 130, 23);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(349, 41, 0, 0);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(266, 155, 0, 0);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 20, 66, 69);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 20, 71, 25);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 300, 45, 16);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 300, 45, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\thank-you-emoji-illustration_csp48936625.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 440, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        confirmedticket jf23 = new confirmedticket();
        int tn = Integer.parseInt(JFrame2.jComboBox4.getSelectedItem().toString());
        String pn = "";String sn = "";
        String date = TicketBookingConformation.jTextField4.getText();
        String dept = "";
        int pnr = 0;
        int sni = 0;
        confirmedticket.jTextField1.setText(TicketBookingConformation.jTextField1.getText());
        confirmedticket.jTextField2.setText(TicketBookingConformation.jTextField2.getText());
        confirmedticket.jTextField3.setText(TicketBookingConformation.jTextField3.getText());
        confirmedticket.jTextField5.setText(date);
        confirmedticket.jTextField7.setText(TicketBookingConformation.jTextField5.getText());
        confirmedticket.jTextField6.setText(TicketBookingConformation.jTextField6.getText());
        int i = 0;
        while(i < tn){
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from train where trainno = " + tn);
           if(rs.next()){
              dept = rs.getString("DeptTime");
           }
           Statement st1 = con.createStatement();
           ResultSet rs1 = st1.executeQuery("Select * from booking where pnr = " + TicketBookingConformation.jLabel11.getText() + " order by seatn desc");
           if(rs1.next()){
              sn = rs1.getString("seatn");
           }
              pnr = Integer.parseInt(TicketBookingConformation.jLabel11.getText());
              sni = Integer.parseInt(sn) - i;
        confirmedticket.jTextField4.setText(pnr + "");
        DefaultTableModel model1 = (DefaultTableModel) confirmedticket.jTable1.getModel();
        TableModel model = (DefaultTableModel) TicketBookingConformation.jTable1.getModel();
        String nta1 = model.getValueAt(i, 0).toString();
        String ata1 = model.getValueAt(i, 1).toString();
        String gta1 = model.getValueAt(i, 2).toString();
        String bta1 = model.getValueAt(i, 3).toString();
        String cta1 = model.getValueAt(i, 4).toString();
        model1.addRow(new Object[]{nta1,ata1,gta1,bta1,cta1,sni});
        }
           catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
        i++;
           }
        dispose();
        jf23.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
