/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame32.java
 *
 * Created on 9 Jun, 2018, 10:39:03 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
public class JFrame32 extends javax.swing.JFrame {

    /** Creates new form JFrame32 */
    public JFrame32() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - HOME PAGE");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel3.setText("Welcome to AIRCTC");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 60, 232, 25);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 66, 69);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 20, 71, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\bookticketn.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 100, 181, 78);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\cancelticketn.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 190, 189, 78);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\prinfon.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 167, 91);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\bhn.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 287, 93);

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Log Out");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 280, 89, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\hqdefault.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 10, 480, 300);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\hqdefault.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 10, 80, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\hqdefault.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 10, 80, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame2 jf2 = new JFrame2();
        jf2.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame24 jf24 = new JFrame24();
        jf24.jLabel2.setText(JFrame1.jTextField1.getText());
        jf24.jLabel2.setVisible(false);
        jf24.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        String a = JFrame1.jTextField1.getText();
        String fn = "";
        String ln = "";
        String cn = "";
        String mn = "";
        PrsnlInfo pi = new PrsnlInfo();
        pi.jLabel1.setText(a);
        pi.jLabel1.setVisible(false);
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from signup where username = '" + a +"'");
           if(rs.next()){
               fn = rs.getString("FirstName");
               ln = rs.getString("LastName");
               cn = rs.getString("Country");
               mn = rs.getString("MobileNo");
   }
           PrsnlInfo.jTextField21.setText(fn);
           PrsnlInfo.jTextField22.setText(ln);
           PrsnlInfo.jTextField23.setText(cn);
           PrsnlInfo.jTextField24.setText(mn);
        }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
        dispose();
        pi.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        BookingHistory bh = new BookingHistory();
        DefaultTableModel m = (DefaultTableModel) bh.jTable1.getModel();
        String tn = "";
        String pnr = "";
        String dtj = "";
        String dtb = "";
        String dtime = "";
        String ctime = "";
        String now = "";
        String n = "";
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from booking where un= '" + JFrame1.jTextField1.getText() + "' group by pnr");
           while(rs.next()){
               n = "Completed";
               tn = rs.getString("TrainNo");
               pnr = rs.getString("PNR");
               dtj = rs.getString("DOJ");
               dtb = rs.getString("DateofBooking");
               Statement st2 = con.createStatement();
               ResultSet rs2 = st2.executeQuery("SELECT * from booking where pnr = " + pnr);
               if(rs2.next()){
                   ctime = rs2.getString("doj");
               }
               Statement st3 = con.createStatement();
               ResultSet rs3 = st3.executeQuery("select now()");
               if(rs3.next()){
                   now = rs3.getString("now()");
               }
   try{
   SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
   Date d1 = sd.parse(ctime);
   Date d2 = sd.parse(now);
   if(d1.after(d2)){
       n = "Pending";
   }
       }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
               m.addRow(new Object[] {tn,dtb,dtj,pnr,n});
   }
               Statement st1 = con.createStatement();
               ResultSet rs1 = st1.executeQuery("Select * from cancelticket where un= '" + JFrame1.jTextField1.getText() + "' group by pnr");
               while(rs1.next()){
                  tn = rs1.getString("TrainNo");
                  pnr = rs1.getString("PNR");
                  dtj = rs1.getString("DOJ");
                  dtb = rs1.getString("DateofBooking");
                  m.addRow(new Object[] {tn,dtb,dtj,pnr,"Cancelled"});
               }
           dispose();
           bh.setVisible(true);
        }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        String u = JFrame1.jTextField1.getText();
        int n = JOptionPane.showConfirmDialog(null, "Are You Sure You want to Log Out from Your Account With UserName " + u);
        if(n == JOptionPane.OK_OPTION){
        dispose();
        JFrame26 jf26 = new JFrame26();
        jf26.setVisible(true);
        JOptionPane.showMessageDialog(null, "Sucessfully Logged Out");
        }
}//GEN-LAST:event_jLabel12MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame32().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
