/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame24.java
 *
 * Created on 8 Jun, 2018, 11:14:52 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class JFrame24 extends javax.swing.JFrame {

    /** Creates new form JFrame24 */
    public JFrame24() {
        initComponents();
        this.setLocationRelativeTo(null);
        String n = "";String ctime = "";String now = "";String pnr = "";
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc","root","root");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from booking where un= '" + JFrame1.jTextField1.getText() + "' group by pnr");
           while(rs.next()){
               n = "Completed";
               pnr = rs.getString("PNR");
               Statement st2 = con.createStatement();
               ResultSet rs2 = st2.executeQuery("SELECT * from booking where pnr = " + pnr);
               if(rs2.next()){
                   ctime = rs2.getString("doj");
               }
               Statement st3 = con.createStatement();
               ResultSet rs3 = st3.executeQuery("select now()");
               if(rs3.next()){
                   now = rs3.getString("now()");
               }
   try{
   SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
   Date d1 = sd.parse(ctime);
   Date d2 = sd.parse(now);
   if(d1.after(d2)){
       n = "Pending";
   }
       }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
               if(n.equalsIgnoreCase("PENDING")){
                  jComboBox1.addItem(pnr);
               }
   }
           int ap = jComboBox1.getItemCount();
           if(ap == 0){
              jComboBox1.addItem("No Tickets Available");
           }
           }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - TICKET CANCELLATION");

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel10.setText("Cancellation of Ticket");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 50, 267, 25);

        jLabel1.setText("PNR:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 170, 50, 14);

        jButton1.setText("Cancel Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 290, 140, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 66, 69);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(500, 20, 71, 24);

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(559, 290, 100, 23);

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel12.setText("Back....");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(940, 310, 74, 25);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(343, 88, 6, 29);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(470, 170, 180, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\cancel-ration-card.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 1010, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CancelTicket jfct = new CancelTicket();
        DefaultTableModel m = (DefaultTableModel) jfct.jTable1.getModel();
        String p = jComboBox1.getSelectedItem().toString();
        String tn = "";
        String tna = "";
        String s = "";
        String d = "";
        String date = "";
        String cdate = "";
        String dtime = "";
        String n = "";
        String a = "";
        String g = "";
        String b = "";
        String ct = "";
        String sn = "";
        String un = jLabel2.getText();
        int itn = 0 ;
        String ctime = "";
        int nt = 0;
        int co = 0;
        try{
           Class.forName("java.sql.DriverManager");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
           if(!p.equalsIgnoreCase("No Tickets Available")){
           Statement st1 = con.createStatement();
           ResultSet rs1 = st1.executeQuery("Select now()");
           if(rs1.next())
               cdate = rs1.getString("now()");
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from booking b, train t where b.pnr = '" + p + "' and b.un = '" + un + "' and b.trainno = t.trainno");
           while(rs.next()){
               nt++;
               tn = rs.getString("trainno");
               tna = rs.getString("t_name");
               s = rs.getString("source");
               d = rs.getString("destination");
               date = rs.getString("DOJ");
   try{
   SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
   Date d1 = sd.parse(cdate);
   Date d2 = sd.parse(date);
   if(d2.after(d1)){
       co++;
   }
       }
   catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
   }
               dtime = rs.getString("depttime");
               n = rs.getString("Name");
               a = rs.getString("Age");
               g = rs.getString("Gender");
               b = rs.getString("Birth");
               ct = rs.getString("CoachType");
               sn = rs.getString("Seatn");
               jfct.jTextField1.setText(tn);
               jfct.jTextField7.setText(tna);
               jfct.jTextField2.setText(s);
               jfct.jTextField3.setText(d);
               jfct.jTextField6.setText(dtime);
               SimpleDateFormat sd1 = new SimpleDateFormat("yyyy-MM-dd");
               Date d3 = sd1.parse(date);
               SimpleDateFormat sd2 = new SimpleDateFormat("yyyy-MM-dd");
               String d4 = sd2.format(d3);
               jfct.jTextField5.setText(d4 + "");
               jfct.jTextField4.setText(p);
               m.addRow(new Object[] {n,a,g,b,ct,sn});
            }
           if(nt == 1 && co == 1){
               dispose();
               jfct.setVisible(true);
            }
 else
           if(nt == 2 && co == 2){
               dispose();
               jfct.setVisible(true);
            }
 else
           if(nt == 3 && co == 3){
               dispose();
               jfct.setVisible(true);
            }
 else
           if(nt == 4 && co == 4){
               dispose();
               jfct.setVisible(true);
            }
 else
           if(nt == 5 && co == 5){
               dispose();
               jfct.setVisible(true);
            }
 else
           if(nt == 6 && co == 6){
               dispose();
               jfct.setVisible(true);
            }
 else
            JOptionPane.showMessageDialog(null, "The Ticket cannot be cancelled as the ticket is already used or in use or the details are incorrect");
            }
 else JOptionPane.showMessageDialog(null, "No Tickets Available for cancellation");
         }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
           System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new JFrame32().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setVisible(true);
}//GEN-LAST:event_jLabel12MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame24().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
