/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrsnlInfo.java
 *
 * Created on Jul 11, 2018, 10:51:46 PM
 */

/**
 *
 * @author Anish Chamaria
 */
import java.sql.*;
import javax.swing.*;
public class PrsnlInfo extends javax.swing.JFrame {

    /** Creates new form PrsnlInfo */
    public PrsnlInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER - PERSONAL INFORMATION");

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setLayout(null);

        jLabel42.setText("First Name:-");
        jPanel7.add(jLabel42);
        jLabel42.setBounds(470, 90, 90, 14);

        jLabel43.setText("Last Name:-");
        jPanel7.add(jLabel43);
        jLabel43.setBounds(470, 120, 100, 14);

        jTextField21.setEditable(false);
        jPanel7.add(jTextField21);
        jTextField21.setBounds(590, 90, 111, 20);

        jTextField22.setEditable(false);
        jPanel7.add(jTextField22);
        jTextField22.setBounds(590, 120, 110, 20);

        jButton6.setText("Change Password");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(510, 210, 140, 23);

        jLabel44.setFont(new java.awt.Font("Ravie", 2, 18));
        jLabel44.setText("Personal Information");
        jPanel7.add(jLabel44);
        jLabel44.setBounds(260, 50, 305, 25);

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\screen-10.57.26[30.04.2018] modified.png")); // NOI18N
        jPanel7.add(jLabel45);
        jLabel45.setBounds(20, 20, 66, 69);

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\Untitled modified1.png")); // NOI18N
        jPanel7.add(jLabel46);
        jLabel46.setBounds(360, 20, 71, 24);

        jLabel47.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18));
        jLabel47.setText("Back....");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47jLabel12MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel47);
        jLabel47.setBounds(640, 310, 74, 25);

        jLabel48.setText("Country:-");
        jPanel7.add(jLabel48);
        jLabel48.setBounds(470, 150, 100, 14);

        jTextField23.setEditable(false);
        jPanel7.add(jTextField23);
        jTextField23.setBounds(590, 150, 109, 20);

        jLabel49.setText("Mobile Number:-");
        jPanel7.add(jLabel49);
        jLabel49.setBounds(470, 180, 100, 14);

        jTextField24.setEditable(false);
        jPanel7.add(jTextField24);
        jTextField24.setBounds(590, 180, 110, 20);

        jLabel1.setEnabled(false);
        jPanel7.add(jLabel1);
        jLabel1.setBounds(24, 167, 23, 19);

        jButton1.setText("Modify Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jButton1.setBounds(510, 250, 140, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\IP Project\\Images and docx\\protection-concept-personal-information-clip-art_csp15115722.jpg")); // NOI18N
        jPanel7.add(jLabel2);
        jLabel2.setBounds(10, 10, 450, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6jButton1ActionPerformed
        // TODO add your handling code here:
        PChange p = new PChange();
        p.jLabel1.setText(jLabel1.getText());
        p.jLabel1.setVisible(false);
        p.setVisible(true);
        dispose();
}//GEN-LAST:event_jButton6jButton1ActionPerformed

    private void jLabel47jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        JFrame32 jf32 = new JFrame32();
        jf32.setVisible(true);
}//GEN-LAST:event_jLabel47jLabel12MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().equalsIgnoreCase("Modify Profile")){
        jTextField21.setEditable(true);
        jTextField22.setEditable(true);
        jTextField23.setEditable(true);
        jTextField24.setEditable(true);
        jButton1.setText("Save Profile");
        }
 else if(jButton1.getText().equalsIgnoreCase("Save Profile")){
    try{
                Class.forName("java.sql.DriverManager");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc" , "root" , "root");
                Statement st = con.createStatement();
                st.executeUpdate("Update signup set FirstName = '" + jTextField21.getText() + "', lastname = '" + jTextField22.getText() + "', country = '" + jTextField23.getText() + "', mobileno = '" + jTextField24.getText() + "' where username = '" + jLabel1.getText() + "'");
                JOptionPane.showMessageDialog(null, "Profile Updated");
                jButton1.setText("Modify Profile");
        jTextField21.setEditable(false);
        jTextField22.setEditable(false);
        jTextField23.setEditable(false);
        jTextField24.setEditable(false);
    }
    catch(Exception e){
       JOptionPane.showMessageDialog(null, e.getMessage());
    }
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrsnlInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel7;
    public static javax.swing.JTextField jTextField21;
    public static javax.swing.JTextField jTextField22;
    public static javax.swing.JTextField jTextField23;
    public static javax.swing.JTextField jTextField24;
    // End of variables declaration//GEN-END:variables

}
